services:

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      -  "5001:5000"
    volumes:
      - ./backend:/app
      - ./model:/app/model
    env_file:
      - .env
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=5000 --reload # TODO: REMOVE --reload FOR PRODUCTION!!!
    restart: unless-stopped
