services:

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      -  "5001:5000"
    env_file:
      - .env
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=5000 --reload # TODO: REMOVE --reload FOR PRODUCTION!!!

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: arrhythmia_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

