name: Deploy Docker Compose App to Azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Docker Compose app
      uses: azure/webapps-deploy@v3
      with:
        app-name: arrhythmia-classifier-app        
        multicontainer-config-file: docker-compose.yml
