name: Deploy Docker Compose App via CLI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy docker-compose to Azure Web App
      run: |
        az webapp config container set \
          --name arrhythmia-classifier-app \
          --resource-group AIProject \
          --multicontainer-config-type compose \
          --multicontainer-config-file docker-compose.yml
