name: Build and deploy Docker Compose app to Azure Web App - AIProjectWebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.AzureAppService_ContainerUsername_bd1f1df181f44c7fbe2b3919635eff76 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7f9923d992bb4715870800a641f6dcc8 }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/arrhythmia-frontend:${{ github.sha }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/arrhythmia-backend:${{ github.sha }}

    - name: Replace image tags in docker-compose.yml
      run: |
        sed -i 's|${TAG}|${{ github.sha }}|g' docker-compose.yml
        sed -i 's|yourdockerhubusername|${{ secrets.DOCKER_USERNAME }}|g' docker-compose.yml

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Docker Compose to Azure Web App
      run: |
        az webapp config container set \
          --resource-group rg_group3 \
          --name AIProjectWebApp \
          --multicontainer-config-type compose \
          --multicontainer-config-file docker-compose.yml
